# -*- coding: utf-8 -*-
"""Week4-A108060066-施靚玟.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wd_mIYc7JAyG7NOVq1D6TZwSQN23ZLFJ
"""

print ("Hello World")